# Generated by Django 3.1.7 on 2021-03-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('author_name', models.ManyToManyField(to='myapp.Author')),
                ('book_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bookuser')),
            ],
        ),
    ]
