# Generated by Django 3.1.7 on 2021-03-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booklibrary_bookuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklibrary',
            name='book_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.bookuser'),
        ),
    ]
